CREATE TABLE credit_txn_dtl (
    id TEXT PRIMARY KEY DEFAULT UPPER(REPLACE(uuid_generate_v4()::TEXT, '-', '')),
    user_id TEXT NOT NULL,
    card_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    txn_cd TEXT NOT NULL,
    txn_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    amount BIGINT DEFAULT 0,
    repay_task TEXT,
    repay_txn_id TEXT,
    created_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    created_by VARCHAR(100) DEFAULT 'SYSTEM',
    modified_date TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    modified_by VARCHAR(100) DEFAULT 'SYSTEM',
    version INT DEFAULT 1,
    is_deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES txn_cards(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES operation_tags(id) ON DELETE CASCADE
);
