CREATE TABLE user_scopes (
    id TEXT PRIMARY KEY DEFAULT ('028PUS' || UPPER(REPLACE(gen_random_uuid()::TEXT, '-', ''))),
    scope_code VARCHAR(25) NOT NULL UNIQUE,
    scope_desc VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    version INT NOT NULL DEFAULT 1,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    is_deleted BOOLEAN DEFAULT FALSE,
    CHECK (id ~ '^028PUS[A-F0-9]{32}$')
);
