CREATE TABLE user_account (
    id TEXT PRIMARY KEY DEFAULT ('052YUA' || UPPER(REPLACE(gen_random_uuid()::TEXT, '-', ''))),
    user_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    user_name VARCHAR(50) NOT NULL UNIQUE,
    email_id VARCHAR(100) NOT NULL UNIQUE,
    profile_img_uri VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    last_login DATE,
    login_count INT DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    is_deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES user_roles(id),
    CHECK (id ~ '^052YUA[A-F0-9]{32}$')
);
